# Generated by Django 6.0 on 2026-01-01 20:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('takoapp1', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='items',
            field=models.ManyToManyField(to='takoapp1.cartitem'),
        ),
    ]
