# Generated by Django 5.2.6 on 2026-01-03 06:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('takoapp1', '0003_remove_order_items_alter_order_cart'),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.CharField(max_length=255)),
                ('is_read', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
